name: bidrag-kodeverk
ingresses:
  - https://bidrag-kodeverk.intern.nav.no
env:
  KODEVERK_URL: https://kodeverk-api.nav.no
  KODEVERK_SCOPE: prod-gcp.team-rocket.kodeverk-api
  JAVA_OPTS: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp -XX:MaxRAMPercentage=80.0